panelstudenta/users/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileSize
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from panelstudenta.models import User
from flask_login import current_user
import re

MIN_PASS = 8
MAX_PASS = 50
MIN_USR = 5
MAX_USR = 20


class RegistrationForm(FlaskForm):
    username = StringField('Nazwa użytkownika',
                           validators=[DataRequired(message='Pole wymagane'), Length(min=MIN_USR, max=MAX_USR,
                           message=f'Nazwa uzytkownika musi zawierać się między {MIN_USR} a {MAX_USR} znaków')],
                           render_kw={"placeholder": "Nazwa użytkownika"})

    email = StringField('Email', validators=[DataRequired(message='Pole wymagane'),
                                             Email(message='Niepoprawny format email')],
                        render_kw={"placeholder": "Email"})

    password = PasswordField(f'Hasło (między {MIN_PASS} a {MAX_PASS} znaków)',
                             validators=[DataRequired(message='Pole wymagane'),
                                         Length(min=MIN_PASS, max=MAX_PASS, message='Hasło musi zawierać się '
                                                                                    f'między {MIN_PASS} a {MAX_PASS} znaków')],
                             render_kw={"placeholder": f'Hasło (między {MIN_PASS} a {MAX_PASS} znaków)'})

    confirm_password = PasswordField('Powtórz hasło', validators=[DataRequired(message='Pole wymagane'),
                                                                  EqualTo('password', message='Hasła '
                                                                                              'muszą się zgadzać')],
                                     render_kw={"placeholder": "Powtórz hasło"})

    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("Nazwa jest już zajęta")

        if re.findall(r"[^a-zA-Z0-9_]", username.data):
            raise ValidationError("Nazwa użytkownika może zawierać tylko angielskie litery, cyfry "
                                  "oraz znak _")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("Email jest już zajęty")

    def validate_password(self, password):
        if re.findall(r"[^a-zA-Z0-9_!@#$%^&*]", password.data):
            raise ValidationError("Hasło może zawierać tylko angielskie litery, cyfry "
                                  "oraz znaki _!@#$%^&*")


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(message='Pole wymagane'), Email(message='Niepoprawny format email')],
                        render_kw={"placeholder": "Email"})
    password = PasswordField('Hasło', validators=[DataRequired(message='Pole wymagane')],
                             render_kw={"placeholder": "Hasło"})
    remember = BooleanField("Zapamiętaj")
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Nazwa użytkownika', validators=[DataRequired(message='Pole wymagane'),
                            Length(min=MIN_USR, max=MAX_USR, message='Nazwa uzytkownika musi zawierać się między '
                                                                           f'{MIN_USR} a {MAX_USR} znaków')],
                           render_kw={"placeholder": "Nazwa użytkownika"})

    email = StringField('Email', validators=[DataRequired(message='Pole wymagane'),
                                             Email(message='Niepoprawny format email')],
                        render_kw={"placeholder": "Email"})

    picture = FileField("Załaduj nowe zdjęcie profilowe", validators=[FileAllowed(['jpg', 'png'],
                                                                                  message="Tylko rozszerzenia jpg i png"),
                                                                      FileSize(max_size=200 * 1000,
                                                                               message="Plik może mieć maksymalnie 200KB")])
    reset_picture = BooleanField("Usuń zdjęcie profilowe")

    submit = SubmitField('Zaktualizuj')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError("Nazwa jest już zajęa")
            if re.findall(r"[^a-zA-Z0-9_]", username.data):
                raise ValidationError("Nazwa użytkownika może zawierać tylko angielskie litery, cyfry "
                                      "oraz znak _")

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError("Email jest już zajęty")


class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(message='Pole wymagane'),
                                             Email(message='Niepoprawny format email')],
                        render_kw={"placeholder": "Email"})
    submit = SubmitField('Wyślij link z dalszymi instrukcjami ')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Hasło', validators=[DataRequired(message='Pole wymagane'),
                                                  Length(min=MIN_PASS, max=MAX_PASS, message='Hasło musi zawierać się '
                                                                                             f'między {MIN_PASS} a {MAX_PASS} znaków')],
                             render_kw={"placeholder": "Hasło"})

    confirm_password = PasswordField('Potwierdź hasło', validators=[DataRequired(message='Pole wymagane'),
                                                                    EqualTo('password', message='Hasła '
                                                                                                'muszą się zgadzać')],
                                     render_kw={"placeholder": "Powtórz hasło"})
    submit = SubmitField('Zresetuj hasło')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Stare hasło', validators=[DataRequired(message='Pole wymagane')],
                                 render_kw={"placeholder": "Sare hasło"})
    password = PasswordField('Nowe hasło', validators=[DataRequired(message='Pole wymagane'),
                                                       Length(min=MIN_PASS, max=MAX_PASS,
                                                              message='Hasło musi zawierać się '
                                                                      f'między {MIN_PASS} a {MAX_PASS} znaków')],
                             render_kw={"placeholder": "Nowe hasło"})

    confirm_password = PasswordField('Powtórz nowe hasło', validators=[DataRequired(message='Pole wymagane'),
                                                                       EqualTo('password', message='Hasła '
                                                                                                   'muszą się zgadzać')],
                                     render_kw={"placeholder": "Powtórz nowe hasło"})
    submit = SubmitField('Zmień hasło')


class DeleteAccountForm(FlaskForm):
    submit = SubmitField('Chcę usunąć konto')

panelstudenta/users/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
import shutil
from flask import render_template, url_for, flash, redirect, Blueprint, request, current_app
from panelstudenta.users.forms import RegistrationForm, UpdateAccountForm, \
    RequestResetForm, ResetPasswordForm, ChangePasswordForm, DeleteAccountForm, LoginForm
from panelstudenta.users.utils import send_reset_email, send_delete_email, save_profile_pic, send_confirm_email
from panelstudenta.general_utils import check_confirmed
from panelstudenta import db, bcrypt
from panelstudenta.models import User, File
from flask_login import current_user, logout_user, login_required, login_user
import os, errno
import datetime
import threading

users = Blueprint('users', __name__, template_folder='templates')


@users.route("/", methods=['GET', 'POST'])
def home():
    """
    Return home page. This page is different for logged and
    not logged in users.
    """
    if current_user.is_authenticated:
        return render_template("home_logged.html")
    form_log = LoginForm()
    if form_log.validate_on_submit():
        user = User.query.filter_by(email=form_log.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form_log.password.data):
            login_user(user, remember=form_log.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.home'))
        else:
            flash('Niepoprawne logowanie. Sprawdź email i hasło', 'danger')
    return render_template("home_login.html", form_log=form_log)


@users.route("/register", methods=['GET', 'POST'])
def register():
    """
    Endpoint for registering new users. If user is already logged in he is
    redirected to home page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form_reg = RegistrationForm()
    if form_reg.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form_reg.password.data).decode('utf-8')
        user = User(username=form_reg.username.data, email=form_reg.email.data, password=hashed_pass, confirmed=False)

        if not os.path.exists(os.path.join(current_app.root_path, "static/users_files", form_reg.username.data)):
            # create directory for uploaded files
            os.makedirs(os.path.join(current_app.root_path, "static/users_files", form_reg.username.data))

        db.session.add(user)
        db.session.commit()

        # Send confirmation email on different thread.
        thread = threading.Thread(target=send_confirm_email, kwargs={'user': user, "app": current_app._get_current_object()})
        thread.start()

        login_user(user)
        flash(f'Utworzono konto dla: {form_reg.username.data}! Na podany adres email za chwilę zostanie wysłana wiadomość z potwierdzeniem.', 'success')
        return redirect(url_for('users.unconfirmed'))
    return render_template("registration.html", form_reg=form_reg, title="Rejestracja")


@users.route('/unconfirmed')
@login_required
def unconfirmed():
    """
    If users email is not confirmed he is shown this page.
    """
    if current_user.confirmed:
        return redirect('users.home')
    return render_template('unconfirmed.html')


@users.route('/confirm/<token>')
@login_required
def confirm_email(token):
    """
   Confirm user's email. If token is expired or invalid or user is already
   confirmed, appropriate message is flashed.
   """
    user = User.verify_token(token)
    if user is None:
        flash("Link aktywujący konto wygasł lub jest nieważny", "warning")
        return redirect(url_for('users.home'))
    if user.confirmed:
        flash('Konto zostało już aktywowane. Proszę się zalogować', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.commit()
        flash('Email został potwierdzony', 'success')
    return redirect(url_for('users.home'))


@users.route('/resend')
@login_required
def resend_confirmation():
    """
    Resend link to confirm email.
    """
    thread = threading.Thread(target=send_confirm_email, kwargs={'user': current_user._get_current_object(), "app": current_app._get_current_object()})
    thread.start()
    flash('Nowy email z potwierdzeniem został wysłany', 'success')
    return redirect(url_for('users.unconfirmed'))


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
@check_confirmed
def account():
    """
    Page to display and update account details.
    """
    form = UpdateAccountForm()

    if form.validate_on_submit():
        path_to_profile_pic = os.path.join(current_app.root_path, "static/profile_pics", current_user.image_file)
        if form.picture.data:
            # save new profile image
            picture_file = save_profile_pic(form.picture.data)
            if current_user.image_file != "default.png":
                # Remove  previous profile picture
                os.remove(path_to_profile_pic)
            current_user.image_file = picture_file
        if form.reset_picture.data and current_user.image_file != "default.png":
            # Reset profile picture
            os.remove(path_to_profile_pic)
            current_user.image_file = "default.png"

        # Change user's name and name of user files directory.
        path_to_user_files = os.path.join(current_app.root_path, "static/users_files", current_user.username)
        path_to_new_user_files = os.path.join(current_app.root_path, "static/users_files", form.username.data)
        os.rename(path_to_user_files, path_to_new_user_files)
        current_user.username = form.username.data

        # Confirm new email
        if form.email.data != current_user.email:
            current_user.confirmed = False
            current_user.confirmed_on = None
            current_user.email = form.email.data

            thread = threading.Thread(target=send_confirm_email, kwargs={'user': current_user._get_current_object(), "app": current_app._get_current_object()})
            thread.start()

            flash("Aby móc dalej korzystać z konta proszę potwierdzić swój nowy adres email!", "info")
        db.session.commit()
        flash("Dane zostały zaktualizowane", "success")
        return redirect(url_for("users.account"))

    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template("account.html", title="Konto", image_file=image_file, form=form)


@users.route("/delete_account", methods=['GET', 'POST'])
@login_required
@check_confirmed
def request_delete():
    """
    Page to request account deletion.
    """
    del_form = DeleteAccountForm()
    if del_form.validate_on_submit():
        thread = threading.Thread(target=send_delete_email, kwargs={'user': current_user._get_current_object(), "app": current_app._get_current_object()})
        thread.start()
        flash("Jeśli podany adres email jest powiązany z kontem została na niego wysłana "
              "informacja dotycząca usuwania konta.", 'info')
        return redirect(url_for('users.account'))
    return render_template("request_delete.html", title="Usuń konto", del_form=del_form)


@users.route("/account/<token>", methods=['GET', 'POST'])
def delete_account(token):
    """
    Delete user's account.
    """
    user = User.verify_token(token)
    if user is None:
        # If token is expired or invalid flash information and redirect to home page.
        flash("Link usuwający konto wygasł lub jest nieważny", "warning")
        return redirect(url_for('users.home'))
    else:
        dir_to_files = os.path.join(current_app.root_path, "static/users_files", user.username)
        if current_user.is_authenticated:
            logout_user()
        # remove files directory of this user
        try:
            shutil.rmtree(dir_to_files)
        except FileNotFoundError:
            pass
        if user.image_file != "default.png":
            # remove profile picture of this user
            path_to_profile_pic = os.path.join(current_app.root_path, "static/profile_pics", user.image_file)
            try:
                os.remove(path_to_profile_pic)
            except OSError:
                pass

        # remove files paths from database
        files_to_del = File.query.filter_by(owner=user).all()
        # remove files path from database
        for f in files_to_del:
            db.session.delete(f)
        db.session.delete(user)
        db.session.commit()
        flash(f'Konto zostało usunięte', 'success')
        return redirect(url_for('users.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def request_reset():
    """
    Page for sending link to reset password for not logged in users.
    """
    if current_user.is_authenticated:
        return render_template("home_logged.html")
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        thread = threading.Thread(target=send_reset_email, kwargs={'user': user, "app": current_app._get_current_object()})
        thread.start()
        flash("Jeśli podany adres email jest powiązany z kontem została na niego wysłana "
              "informacja dotycząca zresetowania hasła.", 'info')
        return redirect(url_for('users.home'))
    return render_template("request_reset.html", title="Zresetuj hasło", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def token_reset(token):
    """
    Reset password.
    """
    if current_user.is_authenticated:
        return render_template("home_logged.html")
    user = User.verify_token(token)
    if user is None:
        # If token is expired or invalid flash information and redirect to home page.
        flash("Link resetujący hasło wygasł lub jest nieważny", "warning")

panelstudenta/users/templates/account.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/forms.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/account.css') }}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col p-0 mt-4">
                    <div class="media media-custom">
                        <img class="rounded-circle account-img" src="{{ image_file }}">
                        <div class="media-body">
                          <h2 class="account-heading">{{ current_user.username }}</h2>
                          <p class="text-secondary">{{ current_user.email }}</p>
                        </div>
                    </div>
             </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-10 col-md-8 p-0 mt-4">
                <div class="update-account-form w-100 p-3">
                    <form method="POST" action="" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <div class="form-group">
                                {{ form.username.label(class="form-control-label") }}
                                {% if form.username.errors %}
                                    {{ form.username(class="form-control form-control-lg is-invalid w-100 inupt-own", value=current_user.username) }}
                                    <div class="invalid-feedback">
                                        {% for error in form.username.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.username(class="form-control form-control-lg w-100 inupt-own", value=current_user.username) }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                    {{ form.email(class="form-control form-control-lg is-invalid w-100 inupt-own", value=current_user.email) }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class="form-control form-control-lg w-100 inupt-own", value=current_user.email) }}
                                {% endif %}
                            </div>
                            <div class="form-group mt-4 d-flex flex-column">
                                {{ form.picture.label(class="mb-1") }}
                                {{ form.picture(class="form-control-file fit-content-width") }}
                                {% if form.picture.errors %}
                                    {% for error in form.picture.errors %}
                                        <span class="text-danger">{{ error }}</span></br>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="form-check mt-4">
                                {{ form.reset_picture(class="form-check-input") }}
                                {{ form.reset_picture.label(class="form-check-label") }}
                            </div>
                        </fieldset>
                        <div class="form-group">
                            {{ form.submit(class="btn submit-button") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col mt-5 mb-4 p-0 justify-content-start">
                <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <div class="d-flex justify-content-between align-items-center flex-wrap">
                        <a href="{{ url_for('users.change_password') }}", class="default-link mr-4">
                            <div class="d-flex flex-row align-items-center justify-content-center btn submit-button">
                                <p class="header-text m-0">Zmień hasło</p>
                            </div>
                        </a>
                        <a href="{{ url_for('users.request_delete') }}", class="default-link">
                            <div class="d-flex flex-row align-items-center justify-content-center btn btn-danger" id="delete-account-button">
                                <p class="header-text m-0">Usuń konto</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

panelstudenta/users/templates/home_logged.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col">
            <h1 class="h1-primary">
                Dostępne aplikacje
            </h1>
        </div>
    </div>
    <div class="row" style="margin-top:70px;">
        <div class="col d-flex flex-wrap justify-content-center align-items-center">
            <div class="d-flex flex-row align-items-center justify-content-start file-row p-1 mb-2">
                <a href="{{ url_for('img2txt.imgtxt') }}" class="default-link file-link w-100">
                    <div class="app-window d-flex align-items-center">
                        <p class="m-0">Wyszukiwarka dokumentów</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

panelstudenta/users/templates/home_login.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/forms.css') }}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row pt-5">
            <div class="col">
                <h1 class="h1-primary">
                    Witaj w panelu studenta! Aby kontynuować musisz się zalogować.
                </h1>
            </div>
        </div>
        <div class="row" style="margin-top:70px;">
            <div class="col d-flex justify-content-center">
                <div class="form-content">
                    <form method="POST" action="">
                        {{ form_log.hidden_tag() }}
                        <fieldset class="form-group">
                            <div class="form-group">
                                {% if form_log.email.errors %}
                                    {{ form_log.email(class="form-control form-control-lg is-invalid w-100 inupt-own") }}
                                    <div class="invalid-feedback">
                                        {% for error in form_log.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form_log.email(class="form-control form-control-lg w-100 inupt-own") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {% if form_log.password.errors %}
                                    {{ form_log.password(class="form-control form-control-lg is-invalid w-100 inupt-own", id="password") }}
                                    <div class="invalid-feedback">
                                        {% for error in form_log.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form_log.password(class="form-control form-control-lg w-100 inupt-own", id="password") }}
                                {% endif %}
                            </div>
                            <div class="form-group d-flex align-items-center">
                                {{ form_log.submit(class="btn submit-button", value="Zaloguj się") }}
                                <div class="form-check d-flex align-items-center ml-1">
                                    {{ form_log.remember(class="form-check-input m-0") }}
                                    {{ form_log.remember.label(class="form-check-label ml-4") }}
                                </div>
                            </div>
                        </fieldset>
                    </form>
                    <div>
                        <a href="{{ url_for('users.request_reset') }}" class="form-links">Zapomniałeś/aś hasła</a>
                        lub <a class="form-links" href="{{ url_for('users.register') }}">Nie masz konta? </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

panelstudenta/users/templates/password_change.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/forms.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row pt-5">
            <div class="col">
                <h1 class="h1-primary">
                    Zmień hasło
                </h1>
            </div>
    </div>
    <div class="row" style="margin-top:70px;">
        <div class="col d-flex justify-content-center">
            <div class="form-content">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {% if form.old_password.errors %}
                                {{ form.old_password(class="form-control form-control-lg is-invalid w-100 inupt-own") }}
                                <div class="invalid-feedback">
                                    {% for error in form.old_password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.old_password(class="form-control form-control-lg w-100 inupt-own") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid w-100 inupt-own") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg w-100 inupt-own") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if form.confirm_password.errors %}
                                {{ form.confirm_password(class="form-control form-control-lg is-invalid w-100  inupt-own") }}
                                <div class="invalid-feedback">
                                    {% for error in form.confirm_password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.confirm_password(class="form-control form-control-lg w-100 inupt-own") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn submit-button") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

panelstudenta/users/templates/unconfirmed.html
{% extends "base.html" %}
{% block content %}
    <h1>Brak potwierdzonego adresu email</h1>
    <br>
    <p>Twój email nie został jeszcze potwierdzony. Sprawdź swoją skrzynkę email (oraz folder spam).</p>
    <p>Wiadomość nie doszła? <a href="{{ url_for('users.resend_confirmation') }}" class="default-link">Wyślij jeszcze raz</a>.</p>
{% endblock content %}