panelstudenta/img2txt/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import current_app
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileSize
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user
import os
import re


class NewFileForm(FlaskForm):
    file = FileField("Dodaj nowy plik", validators=[FileAllowed(['pdf', 'png', 'jpg', 'jpeg'],
                                                     message="Tylko rozszerzenia pdf, jpg, png, jpeg"),
                                         FileSize(max_size=2 * 10**6,
                                                  message="Plik może mieć maksymalnie 2MB"),
                                         DataRequired(message='Pole wymagane')])
    submit = SubmitField('Dodaj plik')

    def validate_file(self, file):
        filename, _ = os.path.splitext(file.data.filename)
        if re.findall(r"[^a-zA-Z0-9_]", filename):
            raise ValidationError("Nazwa pliku może zawierać tylko angielskie litery, cyfry "
                                  "oraz znak _.")
        filepath = os.path.join(current_app.root_path, "static/users_files", current_user.username, file.data.filename)
        path_exists = os.path.exists(filepath)
        if path_exists:
            raise ValidationError("Już istnieje plik o takiej samej nazwie.")


class FindFileForm(FlaskForm):
    searchbox = StringField('Wyszukaj', validators=[DataRequired(message='Pole wymagane')],
                            render_kw={"placeholder": "Co chcesz znaleźć?"})

    amount = IntegerField("Ile plików chcesz wyświetlić", validators=[DataRequired(message='Pole wymagane')])

    def validate_amount(self, amount):
        if type(amount.data) != int:
            raise ValidationError("Ilość wyświetlanych elementów musi być liczbą całkowitą")
        if amount.data < 1:
            raise ValidationError("Trzeba wyświetlić minimum jeden plik")

    submit = SubmitField('Szukaj')

panelstudenta/img2txt/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import render_template, url_for, flash, redirect, \
    request, abort, session, Blueprint, send_from_directory, current_app
from werkzeug.utils import secure_filename
from panelstudenta.img2txt.forms import NewFileForm, FindFileForm
from panelstudenta import db
from panelstudenta.img2txt.utils import token_required
from panelstudenta.models import File, User
from panelstudenta.general_utils import check_confirmed
from flask_login import current_user, login_required
import os
import requests
import base64
import json
from werkzeug.utils import safe_join
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from dotenv import load_dotenv, find_dotenv
import threading

load_dotenv(find_dotenv())


img2txt = Blueprint('img2txt', __name__, template_folder='templates')
URL_NLP = os.environ.get("URL_NLP")


@img2txt.route("/imgtxt/<file_name>", methods=['GET'])
@check_confirmed
@login_required
def file(file_name):
    """
    Display requested file
    """
    filepath = os.path.join(current_app.root_path, "static/users_files", current_user.username)
    if os.path.exists(safe_join(filepath, file_name)):
        return send_from_directory(filepath, file_name)
    else:
        abort(404)


@img2txt.route("/imgtxt/<int:file_id>/delete_file", methods=['POST'])
@login_required
@check_confirmed
def delete_file(file_id):
    """
    Remove user's file.
    """
    file_to_delete = File.query.get_or_404(file_id)
    path_to_file = os.path.join(current_app.root_path, "static/users_files", current_user.username, file_to_delete.name)
    os.remove(path_to_file)
    db.session.delete(file_to_delete)
    db.session.commit()
    flash("Plik został usunięty!", "success")
    return redirect(url_for('img2txt.user_files'))


@img2txt.route("/imgtxt/files", methods=['GET', 'POST'])
@login_required
@check_confirmed
def user_files():
    """
    List and add user files. Adding files works in such a way that
    this app connects with app responsible for extracting text from images.
    That other app processes the file and then returns result to endpoint (img_receive) of
    this app.
    """
    form = NewFileForm()

    # Adding new img2txt
    if form.validate_on_submit():
        if not os.path.exists(os.path.join(current_app.root_path, "static/users_files", current_user.username)):
            # Create file directory for user.
            os.makedirs(os.path.join(current_app.root_path, "static/users_files", current_user.username))
        file_path = os.path.join(current_app.root_path, "static/users_files", current_user.username,
                                 form.file.data.filename)
        # Save file
        form.file.data.save(file_path)

        # Create json file to be sent to image processing app
        with open(file_path, 'rb') as f:
            pdf_b64 = base64.b64encode(f.read()).decode("utf8")
        s = Serializer(current_app.config["SECRET_KEY"], 1800)
        token = s.dumps({"username": current_user.username, "app": "img2txt"},
                        salt=current_app.config['SECURITY_PASSWORD_SALT']).decode('utf-8')
        headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
        filename = secure_filename(form.file.data.filename)
        files = {'file': pdf_b64, "filename": filename, "token": token}

        URL_img = os.environ.get("URL_IMG") + "/" + str(current_user.id)
        try:
            # Connect with app responsible for extracting text from files.
            requests.post(URL_img, data=json.dumps(files), headers=headers)
        except requests.exceptions.ConnectionError:
            flash("Problem z połączeniem z aplikacją zczytującą tekst", "danger")
            os.remove(file_path)
            return redirect(url_for("img2txt.user_files"))

    page = request.args.get('page', 1, type=int)
    files_display = File.query.filter_by(owner=current_user).paginate(page=page, per_page=5)
    return render_template("user_files.html", title="Wyszukiwarka plików", form=form, files_display=files_display)


@img2txt.route("/imgtxt/files/img_receive/<filename>/<user_id>", methods=['POST'])
@token_required("img2txt")
def img_receive(filename, user_id):
    """
    This endpoint receives preprocessed image file from image processing app
    and then sends this data to text processing app where NLP actions will be taken.
    """
    data = request.get_json()
    user = User.query.get(int(user_id))
    s = Serializer(current_app.config["SECRET_KEY"], 1800)
    salt = current_app.config['SECURITY_PASSWORD_SALT']
    def call_nlp(**kwargs):
        """
        This function is called on another thread while response is returned to
        image processing app.
        """
        params = kwargs.get('post_data')
        status_code = int(params['status_code'])
        if status_code < 400:
            # Remove previous status code and token
            # from call received from image processing app.
            params.pop("status_code", None)
            params.pop("token", None)
            if user is not None:
                # Create new token
                token = s.dumps({"username": user.username, "app": "nlp"}, salt=salt).decode('utf-8')
                params["token"] = token
                try:
                    # Connect with app responsible for NLP functionality.
                    requests.post(URL_NLP+"/preprocess/"+filename+"/"+user_id, json=params)
                except requests.exceptions.ConnectionError:
                    file_path = os.path.join(current_app.root_path, "static/users_files", current_user.username,
                                             str(filename))
                    os.remove(file_path)
                    flash("Problem z połączeniem z aplikacją analizującą tekst", "danger")
            else:
                file_path = os.path.join(current_app.root_path, "static/users_files", current_user.username,
                                         str(filename))
                os.remove(file_path)
        else:
            file_path = os.path.join(current_app.root_path, "static/users_files", current_user.username,
                                     str(filename))
            os.remove(file_path)

    # Connect with NLP app on different thread and return response to image processing app.
    with current_app.app_context():
        thread = threading.Thread(target=call_nlp, kwargs={'post_data': data})
        thread.start()
    return {"info": "accepted"}, 202


@img2txt.route("/imgtxt/files/nlp_receive/<filename>/<user_id>", methods=['POST'])
@token_required("nlp")
def nlp_receive(filename, user_id):
    """
    This endpoint receives preprocessed date from NLP app and saves vectorized
    representation of documents in database.
    """
    data = request.get_json()
    status_code = int(data["status_code"])

    if status_code < 400:
        data.pop("status_code", None)
        user = User.query.get(int(user_id))
        new_file = File(name=filename, owner=user, text=data)
        db.session.add(new_file)
        db.session.commit()
    else:
        file_path = os.path.join(current_app.root_path, "static/users_files", current_user.username,
                                 str(filename))
        os.remove(file_path)

    return {"info": "accepted"}, 202


@img2txt.route("/imgtxt", methods=['GET', 'POST'])
@login_required
@check_confirmed
def imgtxt():
    """
    Search files based on user query and display amount of all user files.
    """
    search_form = FindFileForm()
    all_files = File.query.filter_by(owner=current_user).all()

    # Searching documents
    if search_form.validate_on_submit():
        URL_nlp = URL_NLP+"/rank"
        query = search_form.searchbox.data  # user query
        documents_amount = search_form.amount.data if search_form.amount.data < len(all_files) else len(all_files)
        documents = []
        if len(all_files) > 0:
            for f in all_files:
                # Loop over all documents and add them
                # to 'documents' list
                pages = []
                for i in range((len(f.text) - 1) // 2):
                    # text column in File database is a JSON object which
                    # consists of following fields: Document embedding,
                    # tokenized pages from 1st to the last page
                    # and pages embeddings from 1st to the last page.
                    # That's why in the loop over the length of dictionary we
                    # subtract key of document embedding and then divide it by 2
                    # to get the amount of pages.
                    pages.append(f.text[f"Embedding{i}"])
                doc = {"name": f.name,
                       "embedding": f.text["Doc_embedding"],
                       "pages": pages}
                documents.append(doc)

            request_json = {"query": query,
                            "documents": documents,
                            "doc_amount": documents_amount}
            try:
                # Connect to NLP app and find documents most appropriate
                # for user's query.
                response = requests.post(URL_nlp, json=request_json)
            except requests.exceptions.ConnectionError:
                flash("Problem z połączeniem", "danger")
                return redirect(url_for("img2txt.imgtxt"))

            if response.status_code == 200:
                results = response.json()["results"]
            else:
                abort(response.status_code, response.json())
            session["RANKED_DOCS"] = results
            return redirect(url_for("img2txt.imgtxt"))
        else:
            session["NO_DOCS_TO_RANK"] = True
            return redirect(url_for("img2txt.imgtxt"))


    # Rendering template
    title = "Wyszukiwarka plików"
    if session.get("RANKED_DOCS", None) is not None:
        # Template to be rendered when user searched something.

panelstudenta/img2txt/templates/img2txt.html
{% extends "base.html" %}
{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/forms.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/files.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col p-0">
            <div class="fit-content-width mb-3">
                <h2 class="h2-primary">
                    Wyszukiwarka plików
                </h2>
            </div>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col p-0">
            <p>
                W tym miejscu możesz zapisywać pliki w formacie pdf, jpg, png. W wyszukiwarce możesz wpisywać interesujące Cię tematy a aplikacja wyszuka dokumenty najbardziej odpowiadające szukanemu hasłu.
            </p>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col mb-5 p-0" id="search-file-column">
            <div class="mb-5 update-account-form p-3 d-flex flex-column justify-content-start align-items-start">
                <div class="fit-content-width mb-2">
                    <h2 class="h2-primary">
                        Twoje pliki
                    </h2>
                </div>
                {% if user_files_amount > 0 %}
                    <div class="mb-3">
                        <p class="m-0">
                            Ilość plików zapisanych na serwerze: {{ user_files_amount }}.
                        </p>
                    </div>
                    <div>
                        <a href="{{ url_for('img2txt.user_files') }}", class="default-link">
                            <div class="d-flex flex-row align-items-center justify-content-center btn submit-button">
                                <p class="header-text m-0">Przeglądaj swoje pliki</p>
                            </div>
                        </a>
                    </div>
                {% else %}
                    <div>
                        <p>
                            Nie masz jeszcze żadnych plików.
                        </p>
                    </div>
                    <div>
                        <a href="{{ url_for('img2txt.user_files') }}", class="default-link">
                            <div class="d-flex flex-row align-items-center justify-content-center btn submit-button">
                                <p class="header-text m-0">Dodaj nowe pliki</p>
                            </div>
                        </a>
                    </div>
                {% endif %}
            </div>

            <div class="d-flex flex-column update-account-form p-3" id="file-search-div">
                <div>
                    <form method="POST" action="" enctype="multipart/form-data">
                            {{ search_form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="mb-4">Szukaj plików</legend>
                                <div class="form-group">
                                    {{ search_form.searchbox(class="form-control inupt-own", id="document_query") }}
                                    {% if search_form.searchbox.errors %}
                                        {% for error in search_form.searchbox.errors %}
                                            <span class="text-danger">{{ error }}</span></br>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group d-flex align-items-center">
                                    {{ search_form.amount.label(class="mb-0 mr-2") }}
                                    {{ search_form.amount(class="form-control inupt-own", id="document_amount", value=1) }}
                                    {% if search_form.amount.errors %}
                                        {% for error in search_form.amount.errors %}
                                            <span class="text-danger">{{ error }}</span></br>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ search_form.submit(class="btn submit-button") }}
                            </div>
                    </form>
                </div>
                {% if ranked_docs %}
                    {% set ns = namespace(doc_no=1) %}
                    {%  for doc in ranked_docs %}
                        <div class="d-flex flex-row align-items-center justify-content-start file-row p-1 mb-2">
                            <div class="mr-2">
                                {{ ns.doc_no }}.
                            </div>
                            <a href="{{ url_for('img2txt.file', file_name=doc[0]) }}" target=”_blank” class="default-link file-link w-100">
                                <div class="file-name">
                                    <p class="m-0">{{ doc[0] }} </p>
                                </div>
                            </a>
                        </div>
                        {% set ns.doc_no = ns.doc_no+1 %}
                    {% endfor %}
                {% elif no_docs %}
                    <div>
                        <p>Nie masz żadnych dokumentów!!</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

panelstudenta/img2txt/templates/user_files.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/forms.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/files.css') }}">
<script type="text/javascript" src="{{ url_for('static', filename='js/user_files.js') }}"></script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-12 col-sm-5 p-0 justify-content-start align-items-center">
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div id="upload-file">
                     <fieldset class="form-group">
                        <div class="form-group mt-2 d-flex flex-column">
                            {{ form.file(class="form-control-file") }}
                            {% if form.file.errors %}
                                {% for error in form.file.errors %}
                                    <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                            {% endif %}
                        </div>
                     </fieldset>
                     <div class="form-group">
                        {{ form.submit(class="btn submit-button") }}
                     </div>
                </div>
            </form>
        </div>
        <div class="col justify-content-end align-items-center p-0">
            <div class="d-flex justify-content-start justify-content-sm-end align-items-center flex-wrap">
                <a href="{{ url_for('img2txt.imgtxt') }}", class="default-link">
                    <div class="d-flex flex-row align-items-center justify-content-center btn submit-button">
                        <p class="header-text m-0">Wróć do wyszukiwarki plików</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-7 p-0 mb-3 justify-content-start align-items-center">
            <div class="update-account-form w-100 p-3">
                <div class="fit-content-width mb-3">
                    <h2 class="h2-primary">
                        Twoje pliki
                    </h2>
                </div>
                {% if files_display.items|length > 0 %}
                    {% for file in files_display.items %}
                        <div class="d-flex flex-row align-items-center justify-content-between file-row p-1 mb-2">
                            <a href="{{ url_for('img2txt.file', file_name=file.name) }}" target=”_blank” class="default-link file-link">
                                <div class="file-name">
                                    <p class="m-0">{{ file.name }} </p>
                                </div>
                            </a>
                            <button type="button" class="btn btn-danger btn-sm ml-1 delete-button" data-toggle="modal" data-target="#deleteModal" data-filename="{{ file.name }}" data-url="{{ url_for('img2txt.delete_file', file_id=file.id) }}">Usuń</button>
                        </div>

                    {% endfor %}
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content modal-content-own">
                          <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel"></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true" class="modal-close-own">&times;</span>
                            </button>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Nie</button>
                            <form action="" method="POST" id="confirm-delete">
                                <input class="btn btn-danger" type="submit" value="Usuń">
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>


                    <div class="d-flex align-items-center justify-content-center mt-3">
                        {% for page_num in files_display.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                            {% if page_num %}
                                {% if files_display.page == page_num %}
                                  <a class="btn btn-info" href="{{ url_for('img2txt.user_files', page=page_num) }}">{{ page_num }}</a>
                                {% else %}
                                  <a class="btn btn-outline-info" href="{{ url_for('img2txt.user_files', page=page_num) }}">{{ page_num }}</a>
                                {% endif %}
                            {% else %}
                                ...
                            {% endif %}
                        {% endfor %}
                    </div>
                {% else %}
                    <div>
                        Nie masz żadnych plików
                    </div>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock content %}