panelstudenta/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import current_app
from panelstudenta import db, login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.png')
    password = db.Column(db.String(60), nullable=False)
    files = db.relationship('File', backref='owner', lazy=True)
    registered_on = db.Column(db.DateTime, nullable=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, username, email, password, confirmed, confirmed_on=None):
        self.username = username
        self.email = email
        self.password = password
        self.confirmed = confirmed
        self.registered_on = datetime.datetime.now()
        self.confirmed_on = confirmed_on

    def get_token(self, expires_sec=1800):
        s = Serializer(current_app.config["SECRET_KEY"], expires_sec)
        return s.dumps({'user_id': self.id}, salt=current_app.config['SECURITY_PASSWORD_SALT']).decode('utf-8')

    @staticmethod
    def verify_token(token):
        s = Serializer(current_app.config["SECRET_KEY"])
        try:
            user_id = s.loads(token, salt=current_app.config['SECURITY_PASSWORD_SALT'])['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', {self.confirmed}, {self.confirmed_on})"


class File(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False)
    text = db.Column(db.JSON(), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"File('{self.name}', '{self.id}')"

panelstudenta/img2txt/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import current_app
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileSize
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user
import os
import re


class NewFileForm(FlaskForm):
    file = FileField("Dodaj nowy plik", validators=[FileAllowed(['pdf', 'png', 'jpg', 'jpeg'],
                                                     message="Tylko rozszerzenia pdf, jpg, png, jpeg"),
                                         FileSize(max_size=2 * 10**6,
                                                  message="Plik może mieć maksymalnie 2MB"),
                                         DataRequired(message='Pole wymagane')])
    submit = SubmitField('Dodaj plik')

    def validate_file(self, file):
        filename, _ = os.path.splitext(file.data.filename)
        if re.findall(r"[^a-zA-Z0-9_]", filename):
            raise ValidationError("Nazwa pliku może zawierać tylko angielskie litery, cyfry "
                                  "oraz znak _.")
        filepath = os.path.join(current_app.root_path, "static/users_files", current_user.username, file.data.filename)
        path_exists = os.path.exists(filepath)
        if path_exists:
            raise ValidationError("Już istnieje plik o takiej samej nazwie.")


class FindFileForm(FlaskForm):
    searchbox = StringField('Wyszukaj', validators=[DataRequired(message='Pole wymagane')],
                            render_kw={"placeholder": "Co chcesz znaleźć?"})

    amount = IntegerField("Ile plików chcesz wyświetlić", validators=[DataRequired(message='Pole wymagane')])

    def validate_amount(self, amount):
        if type(amount.data) != int:
            raise ValidationError("Ilość wyświetlanych elementów musi być liczbą całkowitą")
        if amount.data < 1:
            raise ValidationError("Trzeba wyświetlić minimum jeden plik")

    submit = SubmitField('Szukaj')

panelstudenta/__init__.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from panelstudenta.config import Config


mail = Mail()
db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.home'
login_manager.login_message = 'Aby dostać się na to stronę, należy się zalogować'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from panelstudenta.users.routes import users
    from panelstudenta.img2txt.routes import img2txt
    app.register_blueprint(users)
    app.register_blueprint(img2txt)

    return app

panelstudenta/users/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
import shutil
from flask import render_template, url_for, flash, redirect, Blueprint, request, current_app
from panelstudenta.users.forms import RegistrationForm, UpdateAccountForm, \
    RequestResetForm, ResetPasswordForm, ChangePasswordForm, DeleteAccountForm, LoginForm
from panelstudenta.users.utils import send_reset_email, send_delete_email, save_profile_pic, send_confirm_email
from panelstudenta.general_utils import check_confirmed
from panelstudenta import db, bcrypt
from panelstudenta.models import User, File
from flask_login import current_user, logout_user, login_required, login_user
import os, errno
import datetime
import threading

users = Blueprint('users', __name__, template_folder='templates')


@users.route("/", methods=['GET', 'POST'])
def home():
    """
    Return home page. This page is different for logged and
    not logged in users.
    """
    if current_user.is_authenticated:
        return render_template("home_logged.html")
    form_log = LoginForm()
    if form_log.validate_on_submit():
        user = User.query.filter_by(email=form_log.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form_log.password.data):
            login_user(user, remember=form_log.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.home'))
        else:
            flash('Niepoprawne logowanie. Sprawdź email i hasło', 'danger')
    return render_template("home_login.html", form_log=form_log)


@users.route("/register", methods=['GET', 'POST'])
def register():
    """
    Endpoint for registering new users. If user is already logged in he is
    redirected to home page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form_reg = RegistrationForm()
    if form_reg.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form_reg.password.data).decode('utf-8')
        user = User(username=form_reg.username.data, email=form_reg.email.data, password=hashed_pass, confirmed=False)

        if not os.path.exists(os.path.join(current_app.root_path, "static/users_files", form_reg.username.data)):
            # create directory for uploaded files
            os.makedirs(os.path.join(current_app.root_path, "static/users_files", form_reg.username.data))

        db.session.add(user)
        db.session.commit()

        # Send confirmation email on different thread.
        thread = threading.Thread(target=send_confirm_email, kwargs={'user': user, "app": current_app._get_current_object()})
        thread.start()

        login_user(user)
        flash(f'Utworzono konto dla: {form_reg.username.data}! Na podany adres email za chwilę zostanie wysłana wiadomość z potwierdzeniem.', 'success')
        return redirect(url_for('users.unconfirmed'))
    return render_template("registration.html", form_reg=form_reg, title="Rejestracja")


@users.route('/unconfirmed')
@login_required
def unconfirmed():
    """
    If users email is not confirmed he is shown this page.
    """
    if current_user.confirmed:
        return redirect('users.home')
    return render_template('unconfirmed.html')


@users.route('/confirm/<token>')
@login_required
def confirm_email(token):
    """
   Confirm user's email. If token is expired or invalid or user is already
   confirmed, appropriate message is flashed.
   """
    user = User.verify_token(token)
    if user is None:
        flash("Link aktywujący konto wygasł lub jest nieważny", "warning")
        return redirect(url_for('users.home'))
    if user.confirmed:
        flash('Konto zostało już aktywowane. Proszę się zalogować', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.commit()
        flash('Email został potwierdzony', 'success')
    return redirect(url_for('users.home'))


@users.route('/resend')
@login_required
def resend_confirmation():
    """
    Resend link to confirm email.
    """
    thread = threading.Thread(target=send_confirm_email, kwargs={'user': current_user._get_current_object(), "app": current_app._get_current_object()})
    thread.start()
    flash('Nowy email z potwierdzeniem został wysłany', 'success')
    return redirect(url_for('users.unconfirmed'))


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
@check_confirmed
def account():
    """
    Page to display and update account details.
    """
    form = UpdateAccountForm()

    if form.validate_on_submit():
        path_to_profile_pic = os.path.join(current_app.root_path, "static/profile_pics", current_user.image_file)
        if form.picture.data:
            # save new profile image
            picture_file = save_profile_pic(form.picture.data)
            if current_user.image_file != "default.png":
                # Remove  previous profile picture
                os.remove(path_to_profile_pic)
            current_user.image_file = picture_file
        if form.reset_picture.data and current_user.image_file != "default.png":
            # Reset profile picture
            os.remove(path_to_profile_pic)
            current_user.image_file = "default.png"

        # Change user's name and name of user files directory.
        path_to_user_files = os.path.join(current_app.root_path, "static/users_files", current_user.username)
        path_to_new_user_files = os.path.join(current_app.root_path, "static/users_files", form.username.data)
        os.rename(path_to_user_files, path_to_new_user_files)
        current_user.username = form.username.data

        # Confirm new email
        if form.email.data != current_user.email:
            current_user.confirmed = False
            current_user.confirmed_on = None
            current_user.email = form.email.data

            thread = threading.Thread(target=send_confirm_email, kwargs={'user': current_user._get_current_object(), "app": current_app._get_current_object()})
            thread.start()

            flash("Aby móc dalej korzystać z konta proszę potwierdzić swój nowy adres email!", "info")
        db.session.commit()
        flash("Dane zostały zaktualizowane", "success")
        return redirect(url_for("users.account"))

    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template("account.html", title="Konto", image_file=image_file, form=form)


@users.route("/delete_account", methods=['GET', 'POST'])
@login_required
@check_confirmed
def request_delete():
    """
    Page to request account deletion.
    """
    del_form = DeleteAccountForm()
    if del_form.validate_on_submit():
        thread = threading.Thread(target=send_delete_email, kwargs={'user': current_user._get_current_object(), "app": current_app._get_current_object()})
        thread.start()
        flash("Jeśli podany adres email jest powiązany z kontem została na niego wysłana "
              "informacja dotycząca usuwania konta.", 'info')
        return redirect(url_for('users.account'))
    return render_template("request_delete.html", title="Usuń konto", del_form=del_form)


@users.route("/account/<token>", methods=['GET', 'POST'])
def delete_account(token):
    """
    Delete user's account.
    """
    user = User.verify_token(token)
    if user is None:
        # If token is expired or invalid flash information and redirect to home page.
        flash("Link usuwający konto wygasł lub jest nieważny", "warning")
        return redirect(url_for('users.home'))
    else:
        dir_to_files = os.path.join(current_app.root_path, "static/users_files", user.username)
        if current_user.is_authenticated:
            logout_user()
        # remove files directory of this user
        try:
            shutil.rmtree(dir_to_files)
        except FileNotFoundError:
            pass
        if user.image_file != "default.png":
            # remove profile picture of this user
            path_to_profile_pic = os.path.join(current_app.root_path, "static/profile_pics", user.image_file)
            try:
                os.remove(path_to_profile_pic)
            except OSError:
                pass

        # remove files paths from database
        files_to_del = File.query.filter_by(owner=user).all()
        # remove files path from database
        for f in files_to_del:
            db.session.delete(f)
        db.session.delete(user)
        db.session.commit()
        flash(f'Konto zostało usunięte', 'success')
        return redirect(url_for('users.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def request_reset():
    """
    Page for sending link to reset password for not logged in users.
    """
    if current_user.is_authenticated:
        return render_template("home_logged.html")
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        thread = threading.Thread(target=send_reset_email, kwargs={'user': user, "app": current_app._get_current_object()})
        thread.start()
        flash("Jeśli podany adres email jest powiązany z kontem została na niego wysłana "
              "informacja dotycząca zresetowania hasła.", 'info')
        return redirect(url_for('users.home'))
    return render_template("request_reset.html", title="Zresetuj hasło", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def token_reset(token):
    """
    Reset password.
    """
    if current_user.is_authenticated:
        return render_template("home_logged.html")
    user = User.verify_token(token)
    if user is None:
        # If token is expired or invalid flash information and redirect to home page.
        flash("Link resetujący hasło wygasł lub jest nieważny", "warning")

panelstudenta/templates/base.html
<!doctype html>
<html lang="pl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Own files -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='js/responsive_navbar.js') }}"></script>

    {% if title %}
     <title>{{ title }}</title>
    {% else %}
        <title>Panel studenta</title>
    {% endif %}
    {% block head %}{% endblock %}
</head>
<body>
    <header class="header-own site-header d-flex align-items-center">
        <div class="container">
            <nav class="big-nav navbar-dark">
                <div class="row w-100  d-flex align-items-center">
                    <div class="col-10 col-md-6 d-flex align-items-center">
                        <div class="fit-content-width logo-big">
                            <a href="{{ url_for('users.home') }}", class="default-link">
                                <div class="d-flex flex-row align-items-center justify-content-center">
                                    <b class="header-text header-bold">Panel studenta</b>
                                    <p class="header-text ml-1 mr-1 mt-0 mb-0">-</p>
                                    <p class="header-text m-0">zapanuj nad studiami</p>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-2 col-md-6 d-flex justify-content-end align-items-center">
                        {% if current_user.is_authenticated %}
                            <button class="navbar-toggler navbar-button" type="button">
                              <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="big-menu">
                                <a href="{{ url_for('users.account') }}", class="default-link">
                                    <div class="d-flex flex-row align-items-center justify-content-center p-2 header-button">
                                        <p class="header-text m-0">Konto</p>
                                    </div>
                                </a>
                                <a href="{{ url_for('users.home') }}", class="default-link">
                                    <div class="d-flex flex-row align-items-center justify-content-center p-2 ml-2 mr-2 header-button">
                                        <p class="header-text m-0">Strona głowna</p>
                                    </div>
                                </a>
                                <a href="{{ url_for('users.logout') }}", class="default-link">
                                    <div class="d-flex flex-row align-items-center justify-content-center p-2 header-button">
                                        <p class="header-text m-0">Wyloguj</p>
                                    </div>
                                </a>
                                {% if not current_user.confirmed %}
                                    <a href="{{ url_for('users.unconfirmed') }}", class="default-link">
                                        <div class="d-flex flex-row align-items-center justify-content-center p-2 header-button">
                                            <p class="header-text m-0">Potwierdź email</p>
                                        </div>
                                    </a>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                {% if current_user.is_authenticated %}
                    <div class="row w-100">
                        <div class="col-12 col-md-0">
                            <div class="small-menu-default">
                                <div class="fit-content-width logo-small">
                                    <a href="{{ url_for('users.home') }}", class="default-link">
                                        <div class="d-flex align-items-center justify-content-center">
                                            <b class="header-text header-bold">Panel studenta</b>
                                        </div>
                                    </a>
                                </div>
                                <a href="{{ url_for('users.account') }}", class="default-link">
                                    <div class="d-flex flex-row align-items-center justify-content-center p-2 header-button">
                                        <p class="header-text m-0">Konto</p>
                                    </div>
                                </a>
                                <a href="{{ url_for('users.home') }}", class="default-link">
                                    <div class="d-flex flex-row align-items-center justify-content-center p-2 ml-2 mr-2 header-button">
                                        <p class="header-text m-0">Strona głowna</p>
                                    </div>
                                </a>
                                <a href="{{ url_for('users.logout') }}", class="default-link">
                                    <div class="d-flex flex-row align-items-center justify-content-center p-2 header-button">
                                        <p class="header-text m-0">Wyloguj</p>
                                    </div>
                                </a>
                                {% if not current_user.confirmed %}
                                    <a href="{{ url_for('users.unconfirmed') }}", class="default-link">
                                        <div class="d-flex flex-row align-items-center justify-content-center p-2 header-button">
                                            <p class="header-text m-0">Potwierdź email</p>
                                        </div>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </nav>
        </div>
    </header>
    <main>
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="row">
                <div class="col-12">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>
    <footer class="d-flex flex-row align-items-center justify-content-center footer-own">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col d-flex justify-content-center align-items-center footer-col-own">
                    <div class="footer-el m-0">
                        &copy 2021 Wojciech Żyła
                    </div>
                    <div class="footer-el m-0">
                        wojciechzyla.mail@gmail.com
                    </div>
                    <div class="footer-el m-0">
                        <a class="default-link footer-link" href="https://www.linkedin.com/in/wojciech-zyla/" target=”_blank”>
                            LinkedIn
                        </a>
                    </div >
                    <div class="footer-el m-0">
                        <a class="default-link footer-link" href="https://github.com/wojciechzyla" target=”_blank”>
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <div id="participants-background"></div>
</body>
</html>